using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BookHaven.Data.Models
{
    public class StaffPerformanceReportModel
    {
        public string StaffName { get; set; }  // Staff Name
        public int SalesCount { get; set; }  // Total Sales Processed by Staff
        public decimal TotalSales { get; set; }  // Total Revenue Generated by Staff
    }
}
